### ISSUE TITLE
UDP Response Variable

### ISSUE THREAD

**Issue by Tommt21** [bitfocus/companion-module-generic-tcp-udp#15]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

A variable to store returned UDP responses from specified connection.

### Usecases

Often when sending UDP messages and acknowledgment or status is returned to the IP and port of sender. A variable would be useful to match or display responses from the device.

**Comment by jswalden** [comment]
UDP is unreliable, and messages may be reordered or even dropped.  So it isn't _technically_ unacceptable to read such variable (however periodically, in whatever sort of background-processy fashion is implemented), and only see whatever happens to have been the most recently received message -- implicitly dropping every message received since the last check.

In the sorts of usually-firewalled uses that Companion's likely to live in, people probably don't actually see much UDP unreliability.  Probably very few drops, and depending on time scales probably not many reorderings.  But Companion actions feel like they're often going to be on such a different time scale, as to magnify connection unreliability beyond what's actually usable/tolerable.

Is that actually good enough for enough real-world uses to add an API like this?

In a world where Companion's only feedback mechanism is writing into (connection-global) variables, I get this is the only way to do it, but it feels much too underpowered and frail to do anything useful with.

**Comment by istnv** [comment]
The UDP mode does not have a 'listener' on the port used when sending messages.
You may be able to send a return UDP message to the Companion API port that sets a custom variable.
